[package]
name = "xkeyclicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rdev = "0.5.1"
tokio = { version = "1", features = ["sync"] }
